### ISSUE TITLE
Failing when installed with pip2020 resolver flag

### ISSUE THREAD

**Issue by frankois** [inveniosoftware/invenio-xrootd#25]
Error message

```
ERROR: Requested xrootd<5.0.0 from https://files.pythonhosted.org/packages/8c/ac/71d16b5bb489685823ff62f20b0d66f12f78420a7626562f44adc1e24ac9/xrootd-4.12.3.tar.gz#sha256=ad015c42caff4720b5d1d3a7a789d4f183c1eec123243a7699ea2c1a8c0e12d1 (from xrootdpyfs>=0.1.2->invenio-xrootd==1.0.0a6) has different version in metadata: '0.0.0'
```

**Comment by topless** [comment]
Here are the findings

1. Looks like the repository has not been fully ported to python 3

1. Latest master has not passed [travis](https://travis-ci.org/github/inveniosoftware/invenio-xrootd/jobs/717879157) for a while.

1. When we try `pip install .`
```bash
ERROR: Command errored out with exit status 1: /Users/chris/.virtualenvs/xroot/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cq/hpzlbysx3qq3fdtjscdfj_zr0000gn/T/pip-install-bod5a7hh/xrootd/setup.py'"'"'; __file__='"'"'/private/var/folders/cq/hpzlbysx3qq3fdtjscdfj_zr0000gn/T/pip-install-bod5a7hh/xrootd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/cq/hpzlbysx3qq3fdtjscdfj_zr0000gn/T/pip-record-k6egeygj/install-record.txt --single-version-externally-managed --compile --install-headers /Users/chris/.virtualenvs/xroot/include/site/python3.6/xrootd Check the logs for full command output.
```

I tried to upgrade `setuptools==49.6.0` and then we get 
```
    ERROR: Command errored out with exit status 1:
     command: /Users/chris/.virtualenvs/xroot/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cq/hpzlbysx3qq3fdtjscdfj_zr0000gn/T/pip-install-kjbvbtf0/xrootd/setup.py'"'"'; __file__='"'"'/private/var/folders/cq/hpzlbysx3qq3fdtjscdfj_zr0000gn/T/pip-install-kjbvbtf0/xrootd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/cq/hpzlbysx3qq3fdtjscdfj_zr0000gn/T/pip-record-v254lzwk/install-record.txt --single-version-externally-managed --compile --install-headers /Users/chris/.virtualenvs/xroot/include/site/python3.6/xrootd
         cwd: /private/var/folders/cq/hpzlbysx3qq3fdtjscdfj_zr0000gn/T/pip-install-kjbvbtf0/xrootd/
    Complete output (22 lines):
    [I] No git repository info found. Trying to interpret VERSION_INFO
    /Users/chris/.virtualenvs/xroot/lib/python3.6/site-packages/setuptools/dist.py:476: UserWarning: The version specified ('') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % version
    running install
    Some dependencies are missing:
    	cmake is missing!
    	openssl development package is missing!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cq/hpzlbysx3qq3fdtjscdfj_zr0000gn/T/pip-install-kjbvbtf0/xrootd/setup.py", line 137, in <module>
        'bdist_wheel': CustomWheelGen
      File "/Users/chris/.virtualenvs/xroot/lib/python3.6/site-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/Users/chris/.pyenv/versions/3.6.10/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/chris/.pyenv/versions/3.6.10/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/chris/.pyenv/versions/3.6.10/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/cq/hpzlbysx3qq3fdtjscdfj_zr0000gn/T/pip-install-kjbvbtf0/xrootd/setup.py", line 83, in run
        raise Exception( 'Dependencies missing!' )
    Exception: Dependencies missing!
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/chris/.virtualenvs/xroot/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cq/hpzlbysx3qq3fdtjscdfj_zr0000gn/T/pip-install-kjbvbtf0/xrootd/setup.py'"'"'; __file__='"'"'/private/var/folders/cq/hpzlbysx3qq3fdtjscdfj_zr0000gn/T/pip-install-kjbvbtf0/xrootd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/cq/hpzlbysx3qq3fdtjscdfj_zr0000gn/T/pip-record-v254lzwk/install-record.txt --single-version-externally-managed --compile --install-headers /Users/chris/.virtualenvs/xroot/include/site/python3.6/xrootd Check the logs for full command output.
```

actions:
- installed cmake locally
- did not manage to install openssl development package

1. When `pip install --use-feature 2020-resolver .`

```
ERROR: Requested xrootd<5.0.0 from https://files.pythonhosted.org/packages/8c/ac/71d16b5bb489685823ff62f20b0d66f12f78420a7626562f44adc1e24ac9/xrootd-4.12.3.tar.gz#sha256=ad015c42caff4720b5d1d3a7a789d4f183c1eec123243a7699ea2c1a8c0e12d1 (from xrootdpyfs>=0.1.2->invenio-xrootd==1.0.0a6) has different version in metadata: '0.0.0'
```

It needs more investigation, probably also `xrootdpyfs`

**Update**
Without `pip install --use-feature 2020-resolver`, in ubuntu, after downloading `cmake`, `uuid` and `uuid-dev` the `pip install .` succeeds.

**Comment by ntarocco** [comment]
We will take care of this in `invenio-app-ils` when working on storing files on EOS.
